version: '3.7'

services:
  web:
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    env_file: ./envs/web.prod.env
    expose:
      - 8000
  db:
    env_file: ./envs/db.prod.env
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web