version: '3.7'

services:
  backend:
    image: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
      build:
        context: .
      depends_on:
        - backend
volumes:
  postgres_data:
