version: '3.7'

services:
  backend:
    command: gunicorn config.wsgi
    env_file: ./envs/prod.env
  postgres:
    env_file: ./envs/prod.env
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile.prod
    env_file: ./envs/prod.env