version: '3.7'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile-backend
      target: base
    command: ./scripts/dev-entrypoint.sh
    env_file: ./.env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./frontend:/app
    working_dir: /app
  postgres:
    image: postgres:11.3-alpine
    ports:
      - 54320:5432
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: ./Dockerfile-web
      target: prod
    command: nginx -g 'daemon off;'
    depends_on:
      - backend
    ports:
      - 8000:80
    env_file: ./.env
volumes:
  postgres_data:
