# Extends docker-compose.yml
version: '3.7'

services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000 --nostatic
    env_file: ./envs/dev.env
    volumes:
      - ./backend:/app
  frontend:
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./frontend:/app
    working_dir: /app
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile.dev
    ports:
      - 8000:80
    env_file: ./envs/dev.env
