version: '3.7'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file: ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3-alpine
    ports:
      - 54320:5432
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    command: nginx -g 'daemon off;'
    depends_on:
      - backend
    ports:
      - 8000:80
    env_file: ./.env
volumes:
  postgres_data:
