version: '3.7'

services:
  backend:
    build:
      target: base
    command: ./scripts/dev-entrypoint.sh
    volumes:
      - ./backend:/app
  frontend:
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./frontend:/app
    working_dir: /app
  nginx:
    build:
      target: base
