version: '3.7'

services:
  web:
    image: web
    build: ./web
    depends_on:
      - db
  db:
    image: postgres:11.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: